- src/DatePickerElement.tsx
Explicit declaration of ParseableDate type.
On latest version importing type is not working anymore.
I believe this will be better as it is a simple type and the date picker is still in lab.
```typescript
export declare type ParseableDate<TDate> =
| string
| number
| Date
| null
| undefined
| TDate;
```
> Explicit ParseableDate type instead of importing from lab

- src/FormContainer.tsx
The children prop was not defined on `FormContainerProps` resulting in type errors when rendering a `FormContainer` with `children`.
> fix: 🐛 use PropsWithChildren for FormContainerProps type

- README.md
- package.json
- yarn.lock
- Adds the `release` package which will handle git tagging and publishing to Github releases. See documentation on how to use it here https://github.com/vercel/release. It essentially boils down to running `yarn release <type>` where `type` is optionally `patch`, `minor`, or `major`.  @dohomi the repo owner is responsible for this since it requires authentication with Github to publish to the release to the repo. Running the command for the first time will begin the auth flow before publishing. 
- Removed existing changelog section from `README.md` in favor of relying on the Github Release notes and commit history.
- Improved `README.md` with some syntax formatting and highlighting. 
Closes #37
> Add `release` package for creating git tags and publishing to github

- .github/workflows/ci.yml
- .gitignore
In order to avoid problems like described in #40 about a build breaking. This workflow will run on all pushes to the repo and on incoming pull requests.
> chore: 🤖 Add github workflow to check commits for failures

- src/PasswordElement.tsx
As written in #41 this will allow to set the color of the Adornment Icon.
I tested also to allow "start" position for Adornment but that makes no sense, so iconColor is only useful prop.
> mod: enable setting of icon color for visibility icons from palette

- src/CheckboxElement.tsx
- src/DatePickerElement.tsx
- src/MultiSelectElement.tsx
- src/SelectElement.tsx
- src/TextFieldElement.tsx
- stories/DatePickerElement.stories.tsx
This fix prevents overriding custom validation messages and settings due to standard values like "This field is required".
Checkout new Story Template for RequiredCustomMessage with and without patch.
Attn: I made this update on 3.6 sources - There were some missing dependencies from storybook and vite which I did not checked in. Best you merge by your decision.
> fix overriding custom validation properties

- src/AutocompleteElement.tsx
The `AutocompleteElement` (with or without the `required` option) will throw an error in the console when a user attempts to use the X to clear the field. This is due to the fact that a null value is being passed to the `onChange` function, which can't handle it properly. This quick fix allows it to work as intended.
> Autocomplete Element: Fix Option Clearing

- packages/rhf-mui/src/DatePickerElement.tsx
- packages/rhf-mui/src/DateTimePickerElement.tsx
Currently, both `DatePickerElement` & `DateTimePickerElement` both do not use the controller `onBlur` method, therefore the `rhf` touched property is not correctly updated, and any validation error are not displayed.
> Set touched property correctly for DatePickerElements & DateTimePickerElements

- .prettierrc.js
- apps/storybook/stories/Switch.stories.tsx
- packages/rhf-mui/src/SwitchElement.tsx
I found this bug when I write
```tsx
<SwitchElement
control={control}
name="switch"
label="Label"
disabled
/>
```
The switch label is disabled but the switch can be triggered
> fix: disabled switch

- packages/rhf-mui/src/PasswordElement.tsx
Added option to customize `PasswordElement` InputAdornment icon.
Closes #122
> Added renderIcon render prop to PasswordElement

- packages/rhf-mui/src/RadioButtonGroup.tsx
Label props were previously only being applied to options with an empty label. But they shoule be applied to all labels to allow customization with MUI props.
> Always apply label props to RadioButtonGroup label

- packages/rhf-mui/src/RadioButtonGroup.tsx
EmptyOptionLabel had a type of 'string' instead of string. 
Current code works fine but typescript will complain if you have anything other than string set as emptyOption.
> EmptyOptionLabel type Fix

- packages/rhf-mui/src/CheckboxElement.tsx
This pull request updates the logic to pass sxProp in checkbox to use the recommended by [material](https://mui.com/system/getting-started/the-sx-prop/#passing-the-sx-prop)
This preserves the usage of callbacks, arrays or objects in the sxProp correctly.
More info: https://github.com/dohomi/react-hook-form-mui/issues/151
> checkbox sxProp handling fix

- packages/rhf-mui/src/MultiSelectElement.tsx
This pull request adds the attribute `preserveOrder` to `MultiSelectElement`. The attribute allows the preservation of the order of displayed selected values according to the sequence they were declared in within `options`, not according to the sequence they were selected in.
In the following example, the selected values were, in order of selection: `divorced`, `single`, `widowed`, `married`.
```typescript
import { Container, Stack } from "@mui/material";
import { FormContainer, MultiSelectElement } from "react-hook-form-mui";
const options = [
{
id: "single",
label: "Single",
},
{
id: "married",
label: "Married",
},
{
id: "divorced",
label: "Divorced",
},
{
id: "widowed",
label: "Widowed",
},
];
export default function Form() {
return (
<Container maxWidth="sm">
<FormContainer>
<Stack …
```
> Allow preservation of selected value order for MultiSelectElement

- packages/rhf-mui/src/TextFieldElement.tsx
This is a common feature on MUI components where you can decide what React element to use for the root component. 
The main purpose of this change is to allow using custom versions of MUI's TextField with TextFieldElement. 
MUI has several ways to customize its components. One of those ways is creating non-global styled versions (using the `styled()` HOC). 
For TextField, choosing that option is more common since this component doesn't allow you to create new "variants". 
With the changes proposed in the PR, developers could pass an "styled" version of their TextFields to the optional `component` prop of `TextFieldElement`.
> Allow TextFieldElement use a different root component instead of TextField

- packages/rhf-mui/src/SelectElement.tsx
Currently if I have options in `SelectElement` defined in separate variable with `as const` => we cannot use them in `SelectElement` :
```tsx
const options = [
{
id: "id-1",
label: "label-1",
},
{
id: "id-2",
label: "label-2",
},
] as const;
// typescript error here:
<SelectElement name="name" options={options} />;
```
Adding `readonly` typescript modifier does not break existing behavior (non-readonly options will work the same as before) and allows passing tuples(array declared with `as const` keyword) to *options* property
> SelectElement: Allow usage with `readonly` options

- packages/rhf-mui/src/AutocompleteElement.tsx
- packages/rhf-mui/src/CheckboxButtonGroup.tsx
- packages/rhf-mui/src/CheckboxElement.tsx
- packages/rhf-mui/src/DatePickerElement.tsx
- packages/rhf-mui/src/DateTimePickerElement.tsx
- packages/rhf-mui/src/MobileDatePickerElement.tsx
- packages/rhf-mui/src/MultiSelectElement.tsx
- packages/rhf-mui/src/RadioButtonGroup.tsx
- packages/rhf-mui/src/SelectElement.tsx
- packages/rhf-mui/src/SliderElement.tsx
- packages/rhf-mui/src/TextFieldElement.tsx
- packages/rhf-mui/src/TextareaAutosizeElement.tsx
- packages/rhf-mui/src/TimePickerElement.tsx
- packages/rhf-mui/src/ToggleButtonGroupElement.tsx
Currently, `parseError` does only allow `string` as `ReturnType`, which limits the option on transforming errors
Updating the `parseError` type declaration to allow `ReactNode` the type of the `helperText` prop/Component.
> Updated parseError type declaration to allow wieder range of return types

- packages/rhf-mui/src/PasswordRepeatElement.tsx
Currently `PasswordRepeatElemet` returns message when does not match with linked field `PasswordElement` without any option to override it. With my PR I am trying to achieve ability to pass custom message, for example when this error needs to be translated.
> Add custom message for invalid PasswordRepeatElement

- packages/rhf-mui/src/DateTimePickerElement.tsx
Fixes #197. For some reason, the `defaultValue` prop is set to `''` (empty string), on the `Controller` component inside `DateTimePickerElement`. By contrast, the corresponding `defaultValue` prop on the `DatePickerElement` and `TimePickerElement` components are both set to `null`.  `DatePickerElement` and `TimePickerElement` both work with the latest version of `@mui/x-date-pickers`, but `DateTimePickerElement` does not.
Changing this `defaultValue` to `null` resolves the inconsistency, and I _believe_ should also make the component work with the latest version of `@mui/x-date-pickers` (although I have not actually tested that claim).
> DateTimePicker: defaultValue is null

- packages/rhf-mui/src/MultiSelectElement.tsx
The error message in the helper text of a MultiSelectElement would persist (without error styling) after the error was no longer applicable.
The top element in each image is the original, the bottom is the fixed version.
Invalid:
Valid:
> Fix persistent error text in MultiSelectElement

- apps/storybook/stories/AutocompleteElement.stories.tsx
- packages/rhf-mui/src/AutocompleteElement.tsx
I've implemented a simple solution to the custom loading spinner problem for the Autocomplete Component.
Also added a storybook example using a MUI Icon as the loading indicator.
Would it make sense to include that as a feature?
> #149 possible custom loader indicator

- packages/rhf-mui/src/RadioButtonGroup.tsx
pr will fix this error:
https://github.com/dohomi/react-hook-form-mui/assets/7282254/3c585cc4-4905-49bd-ab08-15ab607b5432
> fix: fixes error when returnObject is true and value is undefined

- package.json
- packages/rhf-mui/src/AutocompleteElement.tsx
- packages/rhf-mui/src/CheckboxButtonGroup.tsx
- packages/rhf-mui/src/CheckboxElement.tsx
- packages/rhf-mui/src/DatePickerElement.tsx
- packages/rhf-mui/src/DateTimePickerElement.tsx
- packages/rhf-mui/src/MobileDatePickerElement.tsx
- packages/rhf-mui/src/MultiSelectElement.tsx
- packages/rhf-mui/src/PasswordElement.tsx
- packages/rhf-mui/src/PasswordRepeatElement.tsx
- packages/rhf-mui/src/RadioButtonGroup.tsx
- packages/rhf-mui/src/SelectElement.tsx
- packages/rhf-mui/src/SliderElement.tsx
- packages/rhf-mui/src/SwitchElement.tsx
- packages/rhf-mui/src/TextFieldElement.tsx
- packages/rhf-mui/src/TextareaAutosizeElement.tsx
- packages/rhf-mui/src/TimePickerElement.tsx
- packages/rhf-mui/src/ToggleButtonGroupElement.tsx
This PR includes the following changes.
- Replaced Controller with useController for all of the components
- allow ref and inputRef prop using useController, useForkRef and forwardRef 
- inputRef prop is allowed for only those components that support it.
- Fix switchProps.onChange [#203](https://github.com/dohomi/react-hook-form-mui/issues/203)
- Added eslint --fix to run after prettier during each commit. (Reason: indent behavior of prettier is conflicting with eslint. https://stackoverflow.com/questions/43301014/eslint-expected-indentation-of-1-tab-but-found-4-spaces-error)
> Allow ref and inputRef for components

- packages/rhf-mui/src/MobileDatePickerElement.tsx
Fixes the typo in MobileDatePickerElement by replacing field.value with field.ref
> fix: typo in MobileDatePickerElement

- packages/rhf-mui/src/TextareaAutosizeElement.tsx
With this commit "inputProps" prop passed to TextareaAutosizeElement component applies to inner TextField component.
> Fix: apply inputProps to TextareaAutosizeElement

- packages/rhf-mui/src/TextFieldElement.tsx
- packages/rhf-mui/src/useTransform.ts
This PR is inspired by #175 and https://www.react-hook-form.com/advanced-usage/#TransformandParse.
Changes:
Added transform prop to the TextFieldElement component, enabling users to transform input and output values.
Example usage:
```jsx
<TextFieldElement
label="Transform"
name="Transform"
required
transform={{
// Transform input value (number) from react-hook-form to string:
input: (value) => value.toString(),
// Transform output value (string) during onChange event to number:
output: (value) => +value,
}}
/>
```
@dohomi If the proposed changes are fine, then we can add transform prop to other components as well.
> Custom value transform for TextFieldElement

- packages/rhf-mui/src/AutocompleteElement.tsx
- packages/rhf-mui/src/CheckboxButtonGroup.tsx
- packages/rhf-mui/src/CheckboxElement.tsx
- packages/rhf-mui/src/DatePickerElement.tsx
- packages/rhf-mui/src/DateTimePickerElement.tsx
- packages/rhf-mui/src/MobileDatePickerElement.tsx
- packages/rhf-mui/src/MultiSelectElement.tsx
- packages/rhf-mui/src/RadioButtonGroup.tsx
- packages/rhf-mui/src/SelectElement.tsx
- packages/rhf-mui/src/SliderElement.tsx
- packages/rhf-mui/src/SwitchElement.tsx
- packages/rhf-mui/src/TextFieldElement.tsx
- packages/rhf-mui/src/TextareaAutosizeElement.tsx
- packages/rhf-mui/src/TimePickerElement.tsx
- packages/rhf-mui/src/ToggleButtonGroupElement.tsx
This PR makes all components provided by the library pass the `disabled` prop into [useController](https://react-hook-form.com/docs/usecontroller). 
This inherently fixes the issue occurring to date time components outlined in #224.
**Important Note**: According to [useController](https://react-hook-form.com/docs/usecontroller)
> disabled prop will be returned from `field` prop. Controlled input will be disabled and **its value will be omitted from the submission data.**
> Pass disabled to all useController hooks

- packages/rhf-mui/src/DatePickerElement.tsx
- packages/rhf-mui/src/DateTimePickerElement.tsx
- packages/rhf-mui/src/MobileDatePickerElement.tsx
- packages/rhf-mui/src/TimePickerElement.tsx
- packages/rhf-mui/src/utils.ts
This PR introduces a better approach for converting strings to objects within the DatePicker components. This fixes the issue [#235](https://github.com/dohomi/react-hook-form-mui/issues/235) and ensures proper handling for date pickers and other date-related functionalities.
> fix: String to object conversion in Date Pickers

- packages/rhf-mui/src/ToggleButtonGroupElement.tsx
This PR fixes the required validation for ToggleButtonGroupElement and closes [#239](
https://github.com/dohomi/react-hook-form-mui/issues/239)
> fix: required validation in ToggleButtonGroupElement

- packages/rhf-mui/src/CheckboxButtonGroup.tsx
- packages/rhf-mui/src/RadioButtonGroup.tsx
In `CheckboxButtonGroup` and `RadioButtonGroup` there is a conditional that checks if a given element actually has a value and logs a warning if not. However, because it used `!optionKey`, it would give false positives when the value was the number `0`. This PR changes the approach to check for `undefined` instead, thus allowing constructions like `{ id: 0, label: 'None' }` to be rendered without the warning.
> Improves valueKey not found warning logic

- packages/rhf-mui/src/RadioButtonGroup.tsx
When using `<RadioButtonGroup type="number">`, the `value` should be set as a `number` type. However, it is currently being set as a `string` type.
1. Go to the [Value As Number story](https://react-hook-form-material-ui.vercel.app/?path=/story/radiobuttongroup--value-as-number) of `RadioButtonGroup`.
2. Click the "Label 1" radio button.
3. Click the submit button.
4. The value is submitted as the string `"1"` instead of the number `1`.
Before calling `field.onChange(value)`, the `value` is now converted to a number type if `type="number"`.
> Correctly set `<RadioButtonGroup type="number">` value as a number

- packages/rhf-mui/src/RadioButtonGroup.tsx
Fixes #249 
This PR allows users to pass custom required error message and validations to RadioButtonGroup component.
> fix(RadioButtonGroup): Allow passing custom required error message and validations

- packages/rhf-mui/src/SelectElement.tsx
Closes https://github.com/dohomi/react-hook-form-mui/issues/247
There has been a change in React 18.3 where keys should not be spread. 
This PR explicitly sets the key on SelectElement child options
> Fix React key warning in Next.js / React 18.3

- packages/rhf-mui/src/ToggleButtonGroupElement.tsx
Fixed typing on id prop, which didn't allow for number values due to unintentially inheriting the type from default HTML attributes
> Update SingleToggleButtonProps in ToggleButtonGroupElement.tsx

- packages/rhf-mui/src/date-pickers.ts
- packages/rhf-mui/src/index.ts
This marks the react-hook-form-mui main & date-pickers targets as client code, improving compatibility with environments that enable use of React Server Component such as Next.js.
I've confirmed that the "use client" directive indeed is added to `index.js` and `date-pickers.js`  in the `dist/` folder, both for the generated CJS and ESM builds.
Fixes #279
> Add "use client" directives to the main and date-pickers targets

- packages/rhf-mui/src/FormErrorProvider.tsx
Fixes #298
- FormErrorProvider: changed return type of onError function to ReactNode
> fix: changed return type of onError function to ReactNode

- apps/nextjs/package.json
- apps/storybook/package.json
- packages/rhf-mui/package.json
- packages/rhf-mui/src/DatePickerElement.tsx
- packages/rhf-mui/src/DateTimePickerElement.tsx
- packages/rhf-mui/src/MobileDatePickerElement.tsx
- packages/rhf-mui/src/TimePickerElement.tsx
- yarn.lock
Fixes #310
- Upgrade @mui/x-date-pickers package to version 7.17.0
- Adjust validation import paths to align with the latest version
> Bump @mui/x-date-pickers to 7.17.0 for updated validation import paths

- packages/rhf-mui/src/CheckboxButtonGroup.tsx
Fixes #269
- The CheckboxElement was always rendering the label as a string, so the conversion of the label to a string has been removed.
> fix: Checkbox option label not rendering components

- packages/rhf-mui/src/DatePickerElement.tsx
- packages/rhf-mui/src/DateTimePickerElement.tsx
- packages/rhf-mui/src/MobileDatePickerElement.tsx
- packages/rhf-mui/src/TimePickerElement.tsx
Fixes #320
- Skip internal validation for date pickers when value is falsy
> fix: skip internal validation for date pickers when value is falsy

- packages/rhf-mui/src/DatePickerElement.tsx
- packages/rhf-mui/src/DateTimePickerElement.tsx
- packages/rhf-mui/src/MobileDatePickerElement.tsx
- packages/rhf-mui/src/TimePickerElement.tsx
- packages/rhf-mui/src/utils.ts
#320
When date values were provided as strings, internal validation was performed on the string instead of a `Date` object, causing the following components to throw console errors:
- `DatePickerElement`
- `DateTimePickerElement`
- `MobileDatePickerElement`
- `TimePickerElement`
This PR fixes the issue by transforming the value into a `Date` object before performing validation.
@dohomi, it might be worth considering changing the default behavior to stop accepting string values for `x-date-pickers`, as MUI's date picker components themselves do not accept strings by default.
> fix: read string value as date in internal validation

- apps/storybook/stories/MultiSelectElement.stories.tsx
- packages/rhf-mui/src/MultiSelectElement.tsx
I've noticed that with API generated enum types which initialize at index `0`, specifically `MultiSelectElement` tends to misbehave. After some digging I realised that a logical OR operation when rendering chosen `options` would consider the value `'0'` to be falsy, and attempt to render the _whole item_ from `options` instead of just its value. It subsequently causes `[object Object]` to be rendered, allows for selecting said entry more than once without being disabled, and when `showChips` is set to true, it would even outright crash the renderer.
I've changed the operation to be null-coalescing instead, and updated Storybook to advertise the change.
If there's anything I need to clarify, don't hesitate to ask.
> fix: MultiSelectElement does not allow for options w/ { id: '0' }

- apps/nextjs/package.json
- apps/storybook/package.json
- packages/rhf-mui/package.json
- packages/rhf-mui/src/DateTimePickerElement.tsx
- packages/rhf-mui/src/FormContainer.tsx
- yarn.lock
For unknown reason, the import subpath from `react-hook-form/dist/types/fields` failed to resolve in the built package but not in the source code. I've tried checking using both RHF@7.48.2 and @7.54.2 but both seems to be problematic.
To fix this, the import path is changed to simply point to `react-hook-form`
> Fix incorrect RHF dependency by removing references to `../dist/..`

- packages/rhf-mui/src/MultiSelectElement.tsx
https://react-hook-form-material-ui.vercel.app/?path=/docs/select-multiselectelement--docs
**before**:
**after**:
😅
> Add small gap to MultiSelectElement

- packages/rhf-mui/src/AutocompleteElement.tsx
```js
? (props, option, {selected}) => {
return (
<li {...props} key={props.key}>
<Checkbox sx={{marginRight: 1}} checked={selected} />
{getOptionLabel(option)}
</li>
```
the props contain key property, which is the label by default as stated [here](https://mui.com/material-ui/api/autocomplete/#autocomplete-prop-getOptionKey)
related issue: https://github.com/dohomi/react-hook-form-mui/issues/247
> Fix "key" prop warning is being spread on AutocompleteElement

- README.md
The fork step is missing here, contributors can blindly follow the step to clone the upstream repo and find difficulty when pushing.
See updated version: https://github.com/unclebay143/react-hook-form-mui/tree/docs/update-contributing-guide-to-include-fork-step?tab=readme-ov-file#contributing
> docs: update contributing guide with forking instructions

- packages/rhf-mui/package.json
Reverts dohomi/react-hook-form-mui#362
Apologies -- we hadn't fixed the package version incompatibilities yet. This was just our initial commit. We're going to follow up with the fixes in place
> Revert "edit package.json"
